### PR TITLE
Adds Wiki Links and Back Links support

### PR DESCRIPTION
**Pull request by D3vd**
I really like using this theme on top of [obsidian](http://obsidian.md/) and thought it would be pretty cool if the theme could support backlinks between your notes just like the app.

### Create block quotes with the note's file name
Screenshot 2021-04-02 at 2 00 53 PM

### Will be rendered as links in the note's page
Screenshot 2021-04-02 at 2 06 40 PM

### Backlinks will be present on the top of the referenced note
Screenshot 2021-04-02 at 2 09 41 PM

### CODE REVIEW

**Comment by D3vd** [comment]
Hey. The checks seems to be failing due to node version mismatch with a package `gatsby-plugin-catch-links`.

Looks like netlify is using `10.24.0` but the package requires `>=12.13.0`

#### Logs:
```
2:13:55 PM: error gatsby-plugin-catch-links@3.2.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.24.0"
2:13:55 PM: error Found incompatible module.
```

**Comment by mrmartineau** [comment]
Hi @D3vd, thanks so much for adding these features. I will review it over the next few days and see if I can also fix the issues you're experiencing.

**Review by mrmartineau — APPROVED** [review]
@D3vd this is brilliant! Thank you for adding a really useful feature to the theme. I will merge now and cut a release later today.

By the way, I have fixed the Netlify build issue.

**Comment by D3vd** [comment]
Awesome! Thanks

**Comment by mrmartineau** [comment]
@D3vd this has been released in v2.2.0. Please check it out and let me know if there are any issues. Thanks again for the contribution

**Pull request merged**
